### PR TITLE
feat: cosmic-bg integration

### PR DESCRIPTION
**Pull request by mmstick**
This fully integrates with cosmic-bg in its current state.

Requires https://github.com/pop-os/cosmic-bg/pull/16

### CODE REVIEW

**Comment by wash2** [comment]
Seems to work well, I think maybe if you select an image while slide show is toggled, maybe it should un-toggle slideshow?

**Comment by mmstick** [comment]
Indeed. I'll fix this tomorrow morning.

**Comment by wash2** [comment]
Another thing that I've noticed is that if I open up the wallpaper settings and I have a custom source, like: `/home/me/Pictures/cute-wallpapers`, it is overwritten with the default source: `/usr/share/backgrounds/pop/`

**Comment by mmstick** [comment]
@wash2 If today's changes looks good to you, we can these PRs and I'll make followup PRs for any remaining issues in cosmic-settings.

**Review by wash2 — APPROVED** [review]

**Pull request merged**
