### PR TITLE
fix: Duplicate color wallpaper previews

### PR DESCRIPTION
**Pull request by joshuamegnauth54**
Closes: #348

This fix can be simplified by deriving `PartialOrd` for [cosmic_settings_wallpaper::Color](https://github.com/pop-os/cosmic-bg/blob/2259f5ac81099a8215d5ff69cba1ec0d1fd850d1/config/src/lib.rs#L101).  Let me know if I should open a PR for that followed by revising this PR to be a bit simpler.

### CODE REVIEW

**Comment by wash2** [comment]
> Let me know if I should open a PR for that followed by revising this PR to be a bit simpler.

Im in favor of deriving PartialOrd

**Comment by joshuamegnauth54** [comment]
Sounds good. I opened a PR that derives `PartialOrd` [here](https://github.com/pop-os/cosmic-bg/pull/40) and updated the fix in this PR based on that.

**Comment by joshuamegnauth54** [comment]
I bumped `cosmic-bg`, but I think that other dependencies need a bump too:

```error[E0308]: mismatched types
   --> /home/josh/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/ebf5c27/iced/widget/src/scrollable.rs:739:27
    |
739 |         if let Event::Dnd(DndEvent::Offer(_, e)) = &mut event {
    |                           ^^^^^^^^^^^^^^^^^^^^^    ---------- this expression has type `&mut iced_renderer::iced_core::Event`
    |                           |
    |                           expected `DndEvent<DndSurface>`, found `DndEvent<_>`
    |
    = note: `DndEvent<_>` and `dnd::DndEvent<dnd::DndSurface>` have similar names, but are actually distinct types
note: `DndEvent<_>` is defined in crate `dnd`
   --> /home/josh/.cargo/git/checkouts/window_clipboard-a8d336361ed1dc25/a5be704/dnd/src/lib.rs:35:1
    |
35  | pub enum DndEvent<T> {
    | ^^^^^^^^^^^^^^^^^^^^
note: `dnd::DndEvent<dnd::DndSurface>` is defined in crate `dnd`
   --> /home/josh/.cargo/git/checkouts/window_clipboard-a8d336361ed1dc25/7c59b07/dnd/src/lib.rs:35:1
    |
35  | pub enum DndEvent<T> {
    | ^^^^^^^^^^^^^^^^^^^^
    = note: perhaps two different versions of crate `dnd` are being used?```

I don't want to break all of COSMIC by bumping these dependencies. :sweat_smile: This fix is pretty small and also not urgent, so I'll rebase it after the next round of dependency bumps.

Sorry for the hassle!

**Comment by mmstick** [comment]
Ready to rebase

**Comment by joshuamegnauth54** [comment]
Alright. I rebased on master and the fix still works.

**Comment by git-f0x** [comment]
Unrelated, but mentioned in the issue: should an issue be created in cosmic-settings or cosmic-bg for the gradient orientation?

**Comment by mmstick** [comment]
@git-f0x Either

**Review by mmstick — APPROVED** [review]

**Pull request merged**
