### PR TITLE
chore: Remove Graphics Mode and Night Light

### LINKED ISSUE #297: [Displays] Remove Graphics mode and Night Light
Remove graphics mode
- Hybrid graphics has reached the point where other graphics modes have limited (no?) use

Night Light
- Night Light may not make COSMIC V1

### PR DESCRIPTION
**Pull request by git-f0x**
Should close #297.
Seems to work well, but not sure about the async code on the bottom.

Initially wanted to just comment out Night Light related parts, but since some small parts are in `graphics.rs` it might have required a small refactor either way, so I removed them (would have also probably looked messy if commented).

### CODE REVIEW

**Comment by mmstick** [comment]
Keep the night light source code there so it's quick to enable when we do add it to the UI.

**Comment by git-f0x** [comment]
Should I restore `graphics.rs` since it has some small pieces related to Night Light (or maybe rename it to something else)?

**Comment by mmstick** [comment]
It can be renamed to night_light

**Comment by git-f0x** [comment]
Couldn't figure out how to force push, so there are more commits.
Tested without comments, and it displays Night Light on the Page.

**Review by mmstick — APPROVED** [review]

**Comment by mmstick** [comment]
Thanks!

**Comment by git-f0x** [comment]
Sorry for the failing Rustfmt.

**Pull request merged**
