### PR TITLE
fix: Disallow disabling only active display

### PR DESCRIPTION
**Pull request by joshuamegnauth54**
Closes: #299

### CODE REVIEW

**Review by mmstick — CHANGES_REQUESTED** [review]
This check could be moved to the toggle display button. Buttons are insensitive when their `on_press` property is unset.

**Comment by joshuamegnauth54** [comment]
The `Toggler` itself doesn't seem to have `on_press`. Should I wrap it in a `Button`?

**Comment by mmstick** [comment]
No, by not assigning a message, it will use an insensitive style and be unclickable. There should be a `maybe` variant of the method which takes an `Option`.

**Comment by joshuamegnauth54** [comment]
It looks like this now:

disabled_01
disabled_02
disabled_03

The first and third displays are disabled so the toggle still shows. The second display is the only enabled display so the toggle is hidden.

Alsooo I'm not sure why CI is failing. I rebased on master and force pushed too.

**Comment by mmstick** [comment]
Seems we'll need to improve the toggler widget to support an insensitive variant without a message.

**Review by mmstick — APPROVED** [review]

**Pull request merged**
