### PR TITLE
Update libcosmic with some wallpaper page improvements

### PR DESCRIPTION
**Pull request by mmstick**
- Updates libcosmic, which had changes to file chooser dialogs and config subscriptions
- Remove stretch feature from the wallpaper settings UI
- Renames Zoom to Fill in wallpaper settings UI

### CODE REVIEW

**Comment by wash2** [comment]
I think the last commit to the panel should fix the sctk conflicts when vendoring, and undoing the update to the commit should fix the build.

**Comment by gabriele2000** [comment]
> * Remove stretch feature from the wallpaper settings UI
> 
> * Renames Zoom to Fill in wallpaper settings UI

Since you're removing the stretch feature...

"Zoom" has this issue while "Stretch" is perfectly fine.
screenshot-2024-01-29-19-14-22

**Comment by mmstick** [comment]
@gabriele2000 Not able to replicate. Can you shall the image file?

**Comment by gabriele2000** [comment]
> @gabriele2000 Not able to replicate. Can you share the image file?

Wallpaper

**Comment by mmstick** [comment]
@gabriele2000 I was able to replicate with that specific image, though it doesn't affect any of the other images I've tested with. It seems to be a bug within the version of the image crate used by the `cosmic-bg` daemon, but I already planned to update the daemon so this might be resolved once I finish updating it.

**Comment by mmstick** [comment]
@gabriele2000 I was able to resolve the issue in https://github.com/pop-os/cosmic-bg/pull/27

I don't know the cause of the issue though. I noticed that when calling `imageops` functions directly, it scales without issue. But if using resize method from `DynamicImage`, it's broken. This might be a possible test case for reporting a bug in the image crate.

**Pull request merged**
