### PR TITLE
Runtime configurable keyboard shortcuts

### LINKED ISSUE #32: Settings > Input Devices > Keyboard > Keyboard Shortcuts
This page lists categories for keyboard shortcuts. Clicking on any category should take one to the page with the shortcuts for this category. One can access this page by clicking on "View and customize shortcuts" on the [Keyboard page](https://github.com/pop-os/cosmic-settings/issues/9). 

keyboard-shortcuts

Clicking on any category should take one to the [keyboard shortcut category page](https://github.com/pop-os/cosmic-settings/issues/33).

[Mockups in Figma.](https://www.figma.com/file/142SZP1yG2d34SUdDvkaYV/COSMIC-Settings---Developer-Handoff?node-id=7017-225065)

### LINKED ISSUE #33: Settings > Input Devices > Keyboard > Keyboard Shortcuts > Keyboard Shortcut Category
This page lists shortcuts and associated keybindings inside any keyboard shortcut category. Mockup shows "Move window" category as an example. One can access this page by clicking on any keyboard shortcut category on the [Keyboard Shortcuts page](https://github.com/pop-os/cosmic-settings/issues/32). 

keyboard-shortcut-category

Clicking on a shortcut should open ContextDrawer with keybindings for this shortcut action. Users should be able to remove any of the keybindings by clicking on Delete icon button. They should also be able to input the new keybinding by clicking on the Edit icon button or double clicking the shortcut to activate the input. Additionally, there is an option to "Add keybinding" that should allow users to enter the new keybinding by pressing the key combination on their keyboard. 
move-window-down-add-keybinding

If the shortcut is a duplicate of the existing shortcut, show the following dialog after someone releases the keys of the keybinding when entering the shortcut.
Dialog-ShortcutDuplicate

## Custom shortcuts
Custom shortcuts is a category of shortcuts that is empty be default. Below is the view when it is empty. Compared to other categories there is a button to “Add shortcut”.
keyboard-shortcut-category-custom

Clicking on "Add shortcut" opens ContextDrawer where a user can enter shortcut name, command for the shortcut and keybindings.
ContextDrawer-add-custom-shortcut

[Mockups and more details in Figma.](https://www.figma.com/file/142SZP1yG2d34SUdDvkaYV/COSMIC-Settings---Developer-Handoff?node-id=7017-225538)

### LINKED ISSUE #274: [Desktop and Panel] Add Super actions options per design
Dropdown with:

- Open Launcher
- Open Workspaces
- Open Applications

Instead of "Let Super key" the label should be "Super key action" since left and right Super keys do the same thing.

screenshot-2024-05-08-23-45-41

### LINKED ISSUE #373: Match design system padding between the window edge and content area
The area between content and window edges is smaller in the design system. The specified sizes are in the [figma file](https://www.figma.com/design/SkAtS5qlVOGQC0n895AHzX/Design-System-(WIP)?node-id=12307-97968&t=qwAfABAzoCId1nUx-0). There are spacing specifications for single column, two column, and three column views.

The scroll bar will need to be closer to the window edge to achieve the desired padding.

This should reduce the need to wrap most ListItem. [Related ListItem controls responsiveness issue](https://github.com/pop-os/cosmic-settings/issues/372)

Design
image (6)

Current spacing
image (7)

### PR DESCRIPTION
**Pull request by mmstick**
Must be tested alongside package updates to cosmic-comp and cosmic-settings-daemon.

- https://github.com/pop-os/cosmic-settings-daemon/pull/29
- https://github.com/pop-os/cosmic-comp/pull/400

Closes the following issues

- Closes #32
- Closes #33 
- Closes #274
- Closes #373

screenshot-2024-06-20-12-44-49

screenshot-2024-06-20-13-16-22

screenshot-2024-06-20-13-17-36

screenshot-2024-06-20-13-17-06

### CODE REVIEW

**Comment by XV-02** [comment]
Comparing to the [Figma design](https://www.figma.com/design/142SZP1yG2d34SUdDvkaYV/COSMIC-Settings---Developer-Handoff?node-id=7017-225065&t=JNraOY3NBlRKyJ8D-0) I am noticing that categories with modified shortcuts do not report this fact, where as the design notes which categories have modified shortcuts.

**Comment by XV-02** [comment]
I noticed outside of the design:
- If a default key combination is removed, re-adding it will still prompt the "Replace Shortcut" dialogue (to see this, I deleted `Super+Shift+J` from "Move window down" and then manually re-added it.)

**Comment by XV-02** [comment]
After `335a3a7`, which resynced the "Super key" drop down under _Desktop>Desktop and Panel_ with the config file for custom key bindings, I find that I can delete the `Super` key binding (from _Input Devices>Keyboard>View and customize shortcuts>System_) from the field it is assigned to ("Open the app library", "Open the launcher", or "Open the workspace overview"). 

After doing this, the `Super` key automatically defaults back to presenting the launcher; however, the drop down in _Desktop>Desktop and Panel_ does not update so show this, nor does the list of "System" keyboard shortcuts update dynamically to reflect this.

**Comment by XV-02** [comment]
When I click outside of the text field while adding a shortcut, the field blanks. This also happens if I hit return on an invalid shortcut, such as `Super` - which we appear to have reserved.

**Comment by XV-02** [comment]
So, I want to break this down into two broad strokes (as of df1df4f):

1. Functionally

Functionally, this is working well so far. I can create, use, and delete shortcuts; I can modify custom shortcuts; I can overwrite default shortcuts; shortcuts are persistent across sessions. In this regard, I think this is at a place where people can start using it for functionality.

One major functionality issue I have run into so far is that search is too strict - specifically it is caps sensitive. Searching for `move` returns no results, where as `Move` does; Searching for `term` returns "Open a terminal" but `Term` returns "Terminate"

2. Design Compliance

In terms of design compliance, this is off in a number of ways. 

- The edit icons are not present in the context draw. The clear-field button is always present instead of the edit-pencil, and it is not aligned to the text. The spacing on the fields it out of spec (I think this is a general COSMIC issue potentially?). And default shortcuts cannot be directly edited.
 
Side-By-Side_01

- When adding a shortcut, there is no place-holder text for the text field. Additionally, the trash-can/delete icon is immediately present. Design indicates that the desired behaviour is for the delete icon to appear only after the text-field is clicked out of or after the user has submitted a valid shortcut.

Side-By-Side_02

- When selecting a shortcut to edit, the text field should display the prior text with highlighting. At current, it is blanked and a cursor is provided.

Side-By-Side_03

- On Custom Shortcuts specifically, the `Shortcut Name` and `Command` field have the wrong colouration - I think they're supposed to take the primary application window colour from the theme. There is no specific design that I could find for how they look after being filled, so that probably requires follow-up with @pop-os/ux 

Side-By-Side_04

- If I create a shortcut which overwrites a default - e.g. I make `Super + T` close windows, thereby overwriting its terminal-launching function - then only the category I've created the shortcut in reports a modification - e.g. `Manage windows` reports "1 modified", but `System` has no reported modifications.

Oner_05

**Comment by mmstick** [comment]
@XV-02 Ready for another review.

**Comment by mmstick** [comment]
I believe the last remaining UX issues will be resolved in libcosmic.

**Pull request merged**
