### PR TITLE
[Appearance] Interface density

### PR DESCRIPTION
**Pull request by git-f0x**
This adds the 3 interface density options from the designs: Comfortable, Compact and Spacious.
Should be tested alongside pop-os/libcosmic#603.

### CODE REVIEW

**Comment by TheESN** [comment]
Can you show screenshots with examples of these settings please?

**Comment by git-f0x** [comment]
This is pretty much ready, as far as the Settings side is concerned. Could possibly be merged with the `sections.insert(interface_density()),` line being commented out, or wait until everything in libcosmic and apps is polished.
Though merging as is would enable easier testing of what needs tweaks for all COSMIC components, but would introduce something that is a work in progress to users.

**Comment by mmstick** [comment]
I think interface density should be part of Experimental Settings for now.

**Comment by git-f0x** [comment]
I'll try to fix some App Library issues when Spacious, and then I'll try moving it to the Context drawer (above or below icon themes?).

**Comment by mmstick** [comment]
I'll do some testing. Perhaps we don't need it in experimental settings if it's already working well.

**Comment by git-f0x** [comment]
It looks slightly ugly in some cases, but when apps update their libcosmic version, there shouldn't be many things that are cut off or broken. I haven't found anything like that, other than in the App Library, and App Tray (my PR in applets fixes this).

**Comment by mmstick** [comment]
It seems good enough to me.

**Comment by mmstick** [comment]
Thanks!

**Comment by git-f0x** [comment]
I'll work on fixing the App Library, so there isn't missing text on group buttons when Spacious.

**Pull request merged**
