### PR TITLE
[draft] feat: show extended input sources (via toggle)

### PR DESCRIPTION
**Pull request by jmbuhr**
Needs https://github.com/pop-os/xkb-data/pull/4

Todo

- [ ] fix layout of toggle button so that its description doesn't use multiple lines
- [ ] localization of the description

### CODE REVIEW

**Comment by mmstick** [comment]
xkb-data 0.2.0 published to crates.io

**Comment by jmbuhr** [comment]
I'm a bit stuck on rust's dependency management. After updating the crates, I'm getting an error (in `just`, `cargo build` and rust analyzer) that says:

```
error[E0277]: the trait bound `cosmic_bg_config::state::State: CosmicConfigEntry` is not satisfied
   --> cosmic-settings/src/app.rs:275:32
    |
275 |                 .watch_state::<cosmic_bg_config::state::State>(cosmic_bg_config::NAME)
    |                  -----------   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `CosmicConfigEntry` is not implemented for `cosmic_bg_config::state::State`
```

But the definition of `State` in `cosmic-bg` at the commit used in my local `.cargo` cache has

```rust
#[derive(Default, Debug, Deserialize, Serialize, Clone, PartialEq, Setters, CosmicConfigEntry)]
```

and according to `Cargo.lock`, `cosmic-bg-config` is indeed at commit `1dbaf96` (https://github.com/pop-os/cosmic-bg/commit/1dbaf9689d8a6e9a0ddad757ba2a2907b0d4c5ad), which has said line:
https://github.com/pop-os/cosmic-bg/blob/1dbaf9689d8a6e9a0ddad757ba2a2907b0d4c5ad/config/src/state.rs#L7

I would be very happy about any pointers! :)

**Comment by jmbuhr** [comment]
Sidenote: I created this PR because I was very impressed with how smooth the cosmic alpha already runs, so I wanted to contribute small things. If at any point a crate is not ready for external PRs or working through issues like above just creates more work for you folks, feel free to tell me to come back later (or work on my rust skills)!

**Comment by mmstick** [comment]
You only need to update the xkb-data crate, which can be done with `cargo update -p xkb-data`

**Comment by jmbuhr** [comment]
that worked, thanks!

**Comment by FlorianPallas** [comment]
Would fix #606
Only looked for open issues, not PRs.. my bad. Very interested ^^

**Comment by jmbuhr** [comment]
Coincidentally, that's the same keyboard layout why I made the PR. Apologies for the quiet on this, I haven't had the time to properly look into how iced's layouts work to position the button and to fix a bug where the list of active layouts keeps multiplying on toggle.

**Comment by jmbuhr** [comment]
Oh, and one question: What's your policy on localization for new features in PR's? Could I get this to a ready state and hope for someone else to provide the missing translations in a new PR or should all currently available languages already be included in the feature PR?

**Comment by FlorianPallas** [comment]
Is there a downside to always fetching all layouts?
Before I saw your PR I also played around with some ideas and came up with something a little different to your approach, where the toggle would be in the search tab, instead of the page itself.

What's your take on that?
Would make the code a little easier too, since you fetch once and just filter based on the toggle for the search results.

image

**Comment by mmstick** [comment]
I don't expect PRs to come with any localizations. That's for localizers.

**Comment by jmbuhr** [comment]
Closing in favor of https://github.com/pop-os/cosmic-settings/pull/610

**Pull request closed without merging**
